spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db.jocfhsetgbwgaruojagr.supabase.co:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:iqre7tiur4@59}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically update schema (e.g. add password column)
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.security: DEBUG
